processing:
    image_uri: # <your processing ECR image URI>
    entry_point: src/model_build/data_preparation/prepare.py
    s3_input_data_uri: s3://nft-quick-metadata/raw
    s3_output_data_uri: s3://nft-quick-metadata/processed
    parameters:
        MIN_HOLDER_THRESHOLD: 15
        input_folder: /opt/ml/processing/input
        output_folder: /opt/ml/processing/output
        file_name: 3wfew3efbe7uvjnqug6abeiici.json
    instance_count: 1
    instance_type: ml.t3.medium
    base_job_name: frauddetection

training:
    image_uri: # <your training ECR image URI>
    entry_point: train.py
    source_dir: src/model_build/training
    hyperparameters:
        train_size: 0.8
        n_estimators: 150
        remove_multicollinearity: True
        target: display_state
        tracking_uri: http://mlflo-mlflo-1pw3vrqtf5b2a-a49d195bf35b0901.elb.ap-southeast-1.amazonaws.com/
        experiment_name: frauddetection
        save_model_in_registry: True
        model_name: frauddetection-model-1
    instance_count: 1
    instance_type: ml.t3.medium
    # instance_type: local # if you want to run job in a container local
    base_job_name: frauddetection

pipeline:
    name: frauddetection
